name: gimmenow
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  flutter_login: ^1.0.14
  fluttertoast: ^4.0.1
  amazon_cognito_identity_dart: "^0.0.19"
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  rxdart:
  flutter_bloc: ^6.0.5
  equatable: ^1.2.0
  flutter_clean_architecture: ^3.1.0
  get_it: ^4.0.4
  dartz:
  json_annotation:
  intl: ^0.16.0
  intl_translation:
  dio:
  shared_preferences:
  dio_http_cache: ^0.2.11
  flutter_form_builder: ^3.14.1
  mockito: ^4.1.3
  bloc_test: ^7.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_small.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

